package dk.trustworks.newsservice.repository;

import dk.trustworks.newsservice.model.News;
import io.reactivex.Single;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.reactivex.ext.jdbc.JDBCClient;
import io.vertx.reactivex.ext.sql.SQLConnection;

import java.util.List;
import java.util.stream.Collectors;

public class NewsRepository {

    private JDBCClient jdbc;

    public NewsRepository(JDBCClient jdbc) {
        this.jdbc = jdbc;
    }

    private Single<SQLConnection> connect() {
        return jdbc.rxGetConnection()
                .map(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(true)));
    }

    public Single<List<News>> getAll() {
        String sql = "select * from news;";

        return connect().flatMap((SQLConnection connection) -> connection.rxQuery(sql)
                .map(rs -> rs.getRows().stream().map(News::new).collect(Collectors.toList()))
                .doFinally(connection::close));
    }

}
